const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");

const studentModel = new mongoose.Schema({
    firstname: {
        type: String,
        required: [true, "First Name is required"],
        minLength: [4, "First name should be atleast 4 characters long"]
    },
    lastname: {
        type: String,
        required: [true, "Last Name is required"],
        minLength: [4, "Last name should be atleast 4 characters long"]
    },
    contact: {
        type: String,
        required: [true, "Contact is required"],
        maxLength: [10, "Contact must not exceed 10 characters"],
        minLength: [10, "Contact should be atleast 4 characters long"],
    },
    city: {
        type: String,
        required: [true, "City Name is required"],
        minLength: [3, "City should be atleast 3 characters long"]
    },
    gender: {type: String, enum: ["Male","Female","Others"]},
    email: {
        type: String,
        unique: true,
        required: [true, "Email is required"],
        match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Please fill a valid email address']
    },
    password: {
        type: String,
        select: false,
        maxLength: [15,"Passwrod should not exceed more than 15 characters"],
        minLength: [6,"Passwrod should should have atleast 6 characters"],
        //match: []
    },
    resetPasswordToken: {
        type: String,
        default: "0",
    },
    avatar: String,
},
{timestamps:true});

studentModel.pre("save", function() {
    if(!this.isModified("password")){
        return;
    }//it will make the code work only when the password is changed
    let salt = bcrypt.genSaltSync(10);
    this.password = bcrypt.hashSync(this.password, salt);
});
//will work before saving studentModel

studentModel.methods.comparepassword = function(password){
    return bcrypt.compareSync(password, this.password);
};//copares password using bcrypt

studentModel.methods.getjwttoken = function(){
    return jwt.sign({id: this._id}, process.env.JWT_SECRET, {
        expiresIn: process.env.JWT_EXPIRE,
    });
}//a string is saved in the browser it is generated by the person who is logging in

const Student = mongoose.model("student", studentModel);

module.exports = Student;

// {Video 0:15:00}6th