const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");

const studentModel = new mongoose.Schema({
    email: {
        type: String,
        unique: true,
        required: [true, "Email is required"],
        match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/, 'Please fill a valid email address']
    },
    password: {
        type: String,
        select: false,
        maxLength: [15,"Passwrod should not exceed more than 15 characters"],
        minLength: [6,"Passwrod should should have atleast 6 characters"],
        //match: []

    },
},
{timestamps:true});

studentModel.pre("save", function() {
    if(!this.isModified("password")){
        return;
    }//it will make the code work only when the password is changed
    let salt = bcrypt.genSaltSync(10);
    this.password = bcrypt.hashSync(this.password, salt);
});
//will work before saving studentModel

studentModel.methods.comparepassword = function(password){
    return bcrypt.compareSync(password, this.password);
};//copares password using bcrypt

studentModel.methods.getjwttoken = function(){
    return jwt.sign({id: this._id}, process.env.JWT_SECRET, {
        expiresIn: process.env.JWT_EXPIRE,
    });
}//a string is saved in the browser it is generated by the person who is logging in

const Student = mongoose.model("student", studentModel);

module.exports = Student;

//{video 0:07:00}4th